### ISSUE TITLE
Push official image to docker hub

### ISSUE THREAD

**Issue by johnclawson** [corelight/json-tcp-lb#2]
Hey Justin, does Corelight have an official Docker registry? 

I wound up pushing my image to https://hub.docker.com/repository/docker/johnclawson/json-tcp-lb just so that I'd have a public place to pull it from, but an official one would be nice and Docker Hub makes it easy to hook this repo up to an automatic build pipeline.

**Comment by JustinAzoff** [comment]
Yeah, we do.. I'll ask tomorrow how we publish things there.

**Comment by JustinAzoff** [comment]
I sent over a request to our cloud team that manages the dockerhub integration stuff, they should enable it soon.  I  also reworked the Dockerfile  a bit to use a multistage build, so now the resulting image is only  like 8MB.

**Comment by JustinAzoff** [comment]
All set!

```
$ docker run -t -i --rm corelight/json-tcp-lb --help
Unable to find image 'corelight/json-tcp-lb:latest' locally
latest: Pulling from corelight/json-tcp-lb
df20fa9351a1: Pull complete
d11474d26d7b: Pull complete
7a3e4189a7ed: Pull complete
Digest: sha256:b79b3deac755b79d4cb57d89c4356c29fefa1ef245a82d309687306b706552a2
Status: Downloaded newer image for corelight/json-tcp-lb:latest
Usage of /usr/bin/json-tcp-lb:
```
