### ISSUE TITLE
Using Encrypted Connections

### ISSUE THREAD

**Issue by arcsector** [corelight/json-tcp-lb#6]
Is there a way to use this with encrypted data? From what it looks like, in order for the program to see the payload, it needs to be unencrypted. Any details? Thanks!

**Comment by JustinAzoff** [comment]
Hi,

Yes this currently only works for plain TCP connections, but it wouldn't be hard to also support TLS using https://pkg.go.dev/crypto/tls

The only places that currently touch the network are

https://github.com/corelight/json-tcp-lb/blob/faf14a5e4799312f63681e48f5452b9132d881bb/main.go#L237

and

https://github.com/corelight/json-tcp-lb/blob/faf14a5e4799312f63681e48f5452b9132d881bb/main.go#L90

If those were changed to use listen/dial using the tls apis everything else should work the same.

It should even be possible to allow it listen on both plaintext tcp and tls at the same time, as well as export to plain text or tls at the same time.
